Repository fastcampus-mini/credit-market-BE, pull requests merged in 2023-02, with the labels that each got.

#7 #5 - 검색 기능 구현
  build.gradle
  src/main/java/com/example/creditmarket/controller/SearchController.java
  src/main/java/com/example/creditmarket/dto/MainListResponseDto.java
  src/main/java/com/example/creditmarket/repository/OptionRepository.java
  src/main/java/com/example/creditmarket/service/SearchService.java
Labels: enhancement

#11 Feat : 비밀번호 일치확인, 개인정보 수정
  src/main/java/com/example/creditmarket/controller/UserController.java
  src/main/java/com/example/creditmarket/dto/UserInfoResponseDTO.java
  src/main/java/com/example/creditmarket/service/UserService.java
Labels: feature

#12 Feat : UserController Test
  src/main/java/com/example/creditmarket/controller/UserController.java
  src/main/java/com/example/creditmarket/dto/UserInfoResponseDTO.java
  src/main/java/com/example/creditmarket/service/UserService.java
  src/test/java/com/example/creditmarket/controller/UserControllerTest.java
Labels: feature

#13 Feat : Autocomplete Service
  src/main/java/com/example/creditmarket/service/AutoCompleteService.java
Labels: feature

#20 Fix : Allowed unauthorized access to "/search/**" and "/item/**"
  src/main/java/com/example/creditmarket/configuration/AuthenticationConfig.java
Labels: fix

#21 feat:ryusun-product파트 구현
  src/main/java/com/example/creditmarket/controller/ProductController.java
  src/main/java/com/example/creditmarket/dto/FavoriteRequestDto.java
  src/main/java/com/example/creditmarket/dto/OrderRequestDto.java
  src/main/java/com/example/creditmarket/dto/OrderResponseDTO.java
  src/main/java/com/example/creditmarket/dto/ProductDetailDto.java
  src/main/java/com/example/creditmarket/dto/RecommendResponseDto.java
  src/main/java/com/example/creditmarket/entity/EntityOrder.java
  src/main/java/com/example/creditmarket/repository/FavoriteRepository.java
  src/main/java/com/example/creditmarket/repository/OptionRepository.java
  src/main/java/com/example/creditmarket/repository/ProductRepository.java
  src/main/java/com/example/creditmarket/service/mypage/impl/MyPageServiceImpl.java
  src/main/java/com/example/creditmarket/service/product/ProductService.java
  src/main/java/com/example/creditmarket/service/product/impl/ProductServiceImpl.java
Labels: enhancement

#22 Fix : @RequestBody for controller methods
  src/main/java/com/example/creditmarket/controller/UserController.java
  src/main/resources/application.properties
  src/test/java/com/example/creditmarket/controller/UserControllerTest.java
Labels: fix

#24 fix:ryusun - product파트 오류수정
  src/main/java/com/example/creditmarket/controller/ProductController.java
  src/main/java/com/example/creditmarket/service/product/ProductService.java
  src/main/java/com/example/creditmarket/service/product/impl/ProductServiceImpl.java
Labels: enhancement

#26 Feat: #25 - 검색 기능 추가 수정(관심 상품 등록 체크)
  src/main/java/com/example/creditmarket/controller/SearchController.java
  src/main/java/com/example/creditmarket/dto/MainListResponseDto.java
  src/main/java/com/example/creditmarket/repository/OptionRepository.java
  src/main/java/com/example/creditmarket/service/SearchService.java
Labels: enhancement

#28 Feat : insertion of public data via openAPI
  src/main/java/com/example/creditmarket/openAPI/controller/MockController.java
  src/main/java/com/example/creditmarket/openAPI/crawling/CrawlingOpenAPI.java
  src/main/java/com/example/creditmarket/openAPI/crawling/CrawlingRepositoryCompany.java
  src/main/java/com/example/creditmarket/openAPI/crawling/CrawlingRepositoryFProduct.java
  src/main/java/com/example/creditmarket/openAPI/crawling/CrawlingService.java
  src/main/java/com/example/creditmarket/openAPI/dto/TestRequest.java
  src/main/java/com/example/creditmarket/openAPI/dto/TestResponse.java
  src/main/java/com/example/creditmarket/openAPI/repository/TestRepository.java
  src/main/java/com/example/creditmarket/openAPI/service/TestService.java
  src/main/java/com/example/creditmarket/openAPI/service/impl/TestServiceImpl.java
  src/test/java/com/example/creditmarket/controller/UserControllerTest.java
Labels: feature

#29 Remove : deleted unnecessary files regarding mock data
  src/main/java/com/example/creditmarket/openAPI/controller/MockController.java
  src/main/java/com/example/creditmarket/openAPI/dto/TestRequest.java
  src/main/java/com/example/creditmarket/openAPI/dto/TestResponse.java
  src/main/java/com/example/creditmarket/openAPI/service/TestService.java
  src/main/java/com/example/creditmarket/openAPI/service/impl/TestServiceImpl.java
  src/test/java/com/example/creditmarket/controller/UserControllerTest.java
Labels: refactor

#32 Feat: #31 - CORS 처리
  src/main/java/com/example/creditmarket/configuration/AuthenticationConfig.java
Labels: enhancement

#37 Feat : AutoCompleteService 자동완성기능(안쓰일수도)
  src/main/java/com/example/creditmarket/configuration/AuthenticationConfig.java
  src/main/java/com/example/creditmarket/service/AutoCompleteService.java
  src/main/java/com/example/creditmarket/service/UserService.java
  src/main/java/com/example/creditmarket/utils/AutoCompleteUtil.java
Labels: feature

#40 Remove : addkeywords function
  src/main/java/com/example/creditmarket/service/Impl/AutoCompleteServiceImpl.java
Labels: fix

#41 Fix : primitive -> non-primitive and AutocompleteImpl
  src/main/java/com/example/creditmarket/entity/EntityFProduct.java
  src/main/java/com/example/creditmarket/entity/EntityOrder.java
  src/main/java/com/example/creditmarket/service/AutoCompleteService.java
  src/main/java/com/example/creditmarket/service/Impl/AutoCompleteServiceImpl.java
Labels: fix

#43 Feat: #42 - 검색 결과 항목 추가
  src/main/java/com/example/creditmarket/dto/response/MainListResponseDTO.java
  src/main/java/com/example/creditmarket/service/Impl/SearchServiceImpl.java
Labels: enhancement

#46 fix:ryusun - 오류 수정
  src/main/java/com/example/creditmarket/controller/ProductController.java
  src/main/java/com/example/creditmarket/dto/response/ProductDetailResponseDTO.java
  src/main/java/com/example/creditmarket/repository/FProductRespository.java
  src/main/java/com/example/creditmarket/repository/OptionRepository.java
  src/main/java/com/example/creditmarket/repository/ProductRepository.java
  src/main/java/com/example/creditmarket/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/creditmarket/service/ProductService.java
Labels: fix

#49 fix:ryusun - 오류수정
  src/main/java/com/example/creditmarket/controller/ProductController.java
  src/main/java/com/example/creditmarket/service/Impl/ProductServiceImpl.java
  src/main/java/com/example/creditmarket/service/ProductService.java
Labels: fix

#54 Fix : include token when logged in
  src/main/java/com/example/creditmarket/controller/UserController.java
  src/main/java/com/example/creditmarket/dto/response/LoginResponseDTO.java
Labels: fix

#56 Fix : return username instead of useremail when log in
  src/main/java/com/example/creditmarket/controller/UserController.java
  src/main/java/com/example/creditmarket/dto/response/LoginResponseDTO.java
  src/main/java/com/example/creditmarket/service/Impl/UserServiceImpl.java
  src/main/java/com/example/creditmarket/service/UserService.java
  src/test/java/com/example/creditmarket/controller/UserControllerTest.java
Labels: fix

#58 Feat: #57 - 추천 상품 목록 api 에 관심 상품 등록 값 추가
  src/main/java/com/example/creditmarket/dto/response/RecommendResponseDTO.java
  src/main/java/com/example/creditmarket/service/Impl/ProductServiceImpl.java
Labels: enhancement

#60 Feat: #59 - 상품 리스트 DTO 변수명 통일
  src/main/java/com/example/creditmarket/dto/response/MainListResponseDTO.java
Labels: enhancement

#63 Feat : ProjectStructure.md
  ProjectStructure.md
Labels: feature

#64 Fix : UserTestController - Added /userinfo and urls for other tests
  src/test/java/com/example/creditmarket/controller/UserControllerTest.java
Labels: fix

#67 Feat : Autocomplete
  src/main/java/com/example/creditmarket/controller/SearchController.java
Labels: feature

#69 Feat : Autocomplete, sendNewPasswordAuth
  src/main/java/com/example/creditmarket/configuration/AuthenticationConfig.java
  src/main/java/com/example/creditmarket/controller/SearchController.java
  src/main/java/com/example/creditmarket/controller/UserController.java
  src/main/java/com/example/creditmarket/dto/request/AutoCompleteRequestDTO.java
  src/main/java/com/example/creditmarket/entity/EntityUser.java
  src/main/java/com/example/creditmarket/service/Impl/AutoCompleteServiceImpl.java
  src/main/java/com/example/creditmarket/service/Impl/UserServiceImpl.java
  src/main/java/com/example/creditmarket/service/UserService.java
  src/main/java/com/example/creditmarket/utils/AutoCompleteUtil.java
  src/main/java/com/example/creditmarket/utils/RandomCertNumber.java
Labels: feature
